[phases.setup]
nixPkgs = ["nodejs_20", "chromium", "nss", "nspr", "atk", "cups", "libdrm", "dbus", "libxkbcommon", "gtk3", "pango", "cairo", "glib", "alsa-lib", "expat"]

[phases.install]
cmds = ["npm install"]

[start]
cmd = "node server.js"

[variables]
PUPPETEER_EXECUTABLE_PATH = "/nix/var/nix/profiles/default/bin/chromium"
PUPPETEER_SKIP_CHROMIUM_DOWNLOAD = "true"
